#!/bin/bash -e

cd ../build/

# Start registry
if sudo netstat -lnp | grep -q rmiregistry; then
    echo "RMI registry already initialized on port 1099"
else
  echo "Initializing RMI registry on port 1099"
  rmiregistry &
fi

# Start stores
gnome-terminal -- java -Djava.rmi.server.codebase=file:./ store.Store 224.0.0.0 3000 127.0.0.1 9000
gnome-terminal -- java -Djava.rmi.server.codebase=file:./ store.Store 224.0.0.0 3000 127.0.0.2 9000
gnome-terminal -- java -Djava.rmi.server.codebase=file:./ store.Store 224.0.0.0 3000 127.0.0.3 9000
gnome-terminal -- java -Djava.rmi.server.codebase=file:./ store.Store 224.0.0.0 3000 127.0.0.4 9000
