#!/bin/bash -e

cd ../build/

if [ $1 == "1" ]; then
  java TestClient 127.0.0.1:3100 $2 $3
elif [ $1 == "2" ]; then
  java TestClient 127.0.0.2:3100 $2 $3
elif [ $1 == "3" ]; then
  java TestClient 127.0.0.3:3100 $2 $3
elif [ $1 == "4" ]; then
  java TestClient 127.0.0.4:3100 $2 $3
else
  echo "Command not found"
fi
